# Generated by Django 2.2.1 on 2019-05-13 10:27
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='Approach',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('uses_external_data', models.BooleanField()),
                (
                    'manuscript',
                    models.FileField(
                        upload_to=core.models.submission_csv_file_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=['pdf']
                            )
                        ],
                    ),
                ),
            ],
            options={'verbose_name_plural': 'approaches'},
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('accepting_submissions', models.BooleanField(default=False)),
                ('data_file', models.FileField(upload_to=core.models.task_data_file_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('institution', models.CharField(max_length=100)),
                (
                    'creator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'task',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Task'),
                ),
                (
                    'users',
                    models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'recipient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='received_invites',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'sender',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sent_invites',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'csv',
                    models.FileField(
                        upload_to=core.models.submission_csv_file_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=['csv']
                            )
                        ],
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('scoring', 'Scoring'),
                            ('failed', 'Failed'),
                            ('succeeded', 'Succeeded'),
                        ],
                        default='scoring',
                        max_length=20,
                    ),
                ),
                (
                    'approach',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.Approach'
                    ),
                ),
                (
                    'task',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Task'),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('score', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('fail_reason', models.TextField(blank=True)),
                (
                    'submission',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.Submission'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='approach',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Task'),
        ),
        migrations.AddField(
            model_name='approach',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
    ]
