# Generated by Django 2.2 on 2019-06-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('core', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(model_name='team', name='task'),
        migrations.AlterField(
            model_name='score',
            name='submission',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='scores',
                to='core.Submission',
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='challenge',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='tasks',
                to='core.Challenge',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='challenge',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Challenge'
            ),
            preserve_default=False,
        ),
    ]
