# Generated by Django 2.2.2 on 2019-06-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='team', name='institution_url', field=models.URLField(blank=True)
        ),
        migrations.AlterField(
            model_name='team',
            name='institution',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
