# Generated by Django 2.2 on 2019-06-20 22:50
from typing import List

from django.db import migrations
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):

    dependencies = [('core', '0002_auto_20190619_1328'), ('core', '0003_auto_20190620_1822')]

    operations: List[Operation] = []
