# Generated by Django 2.2 on 2019-06-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('core', '0002_auto_20190619_1328'), ('core', '0003_auto_20190620_1822')]

    operations = []
