# Generated by Django 3.0.3 on 2020-02-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0003_insert_challenge_slugs')]

    operations = [
        migrations.AlterField(
            model_name='challenge', name='slug', field=models.SlugField(unique=True)
        )
    ]
