# Generated by Django 2.2.2 on 2019-06-25 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('core', '0004_merge_20190620_2250')]

    operations = [
        migrations.RenameField(model_name='submission', old_name='user', new_name='creator'),
        migrations.RenameField(
            model_name='task', old_name='accepting_submissions', new_name='active'
        ),
        migrations.RenameField(
            model_name='task', old_name='data_file', new_name='test_ground_truth_file'
        ),
        migrations.RemoveField(model_name='submission', name='task'),
        migrations.AddField(
            model_name='challenge', name='active', field=models.BooleanField(default=False)
        ),
        migrations.AddField(
            model_name='score',
            name='overall_score',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission', name='accepted_terms', field=models.BooleanField(default=False)
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task', name='visible', field=models.BooleanField(default=False)
        ),
        migrations.AlterField(
            model_name='score',
            name='submission',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='core.Submission'
            ),
        ),
        migrations.AlterField(
            model_name='team', name='name', field=models.CharField(max_length=100)
        ),
        migrations.AlterUniqueTogether(name='team', unique_together={('challenge', 'name')}),
    ]
