# Generated by Django 2.2.2 on 2019-06-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0005_auto_20190625_0209')]

    operations = [
        migrations.RemoveField(model_name='submission', name='status'),
        migrations.AddField(
            model_name='score',
            name='status',
            field=models.CharField(
                choices=[
                    ('queued', 'Queued for scoring'),
                    ('scoring', 'Scoring'),
                    ('internal_failure', 'Internal failure'),
                    ('failed', 'Failed'),
                    ('succeeded', 'Succeeded'),
                ],
                default='queued',
                max_length=20,
            ),
        ),
    ]
