# Generated by Django 2.2.2 on 2019-06-25 15:32
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [('core', '0006_auto_20190625_0306')]

    operations = [
        migrations.RemoveField(model_name='submission', name='csv'),
        migrations.AddField(
            model_name='approach',
            name='manuscript_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='test_prediction_file',
            field=models.FileField(default='', upload_to=core.models.submission_csv_file_upload_to),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='test_prediction_file_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
