# Generated by Django 2.2.2 on 2019-06-25 15:39
import django.core.validators
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [('core', '0007_auto_20190625_1532')]

    operations = [
        migrations.AlterField(
            model_name='approach',
            name='manuscript',
            field=models.FileField(
                blank=True,
                max_length=200,
                upload_to=core.models.submission_file_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])
                ],
            ),
        ),
        migrations.AlterField(
            model_name='approach',
            name='manuscript_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
