# Generated by Django 2.2.2 on 2019-06-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0008_auto_20190625_1539')]

    operations = [
        migrations.AlterField(
            model_name='approach',
            name='manuscript_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        )
    ]
