# Generated by Django 2.2.2 on 2019-06-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0009_auto_20190625_1642')]

    operations = [
        migrations.AlterField(
            model_name='approach',
            name='manuscript_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        )
    ]
