# Generated by Django 2.2.2 on 2019-06-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0010_auto_20190625_1706')]

    operations = [
        migrations.RemoveField(model_name='score', name='status'),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(
                choices=[
                    ('queued', 'Queued for scoring'),
                    ('scoring', 'Scoring'),
                    ('internal_failure', 'Internal failure'),
                    ('failed', 'Failed'),
                    ('succeeded', 'Succeeded'),
                ],
                default='queued',
                max_length=20,
            ),
        ),
    ]
