# Generated by Django 2.2.2 on 2019-06-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0011_auto_20190625_1745')]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='test_prediction_file_name',
            field=models.CharField(max_length=200),
        )
    ]
