# Generated by Django 2.2.2 on 2019-06-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0012_auto_20190625_1804')]

    operations = [
        migrations.AlterField(model_name='score', name='overall_score', field=models.FloatField())
    ]
