# Generated by Django 2.2.2 on 2019-06-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0014_auto_20190626_1525')]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        )
    ]
