# Generated by Django 2.2.2 on 2019-06-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0016_auto_20190626_2117')]

    operations = [
        migrations.AddField(
            model_name='task',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        )
    ]
