# Generated by Django 2.2.2 on 2019-06-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('core', '0017_task_short_description')]

    operations = [migrations.RenameField(model_name='task', old_name='visible', new_name='public')]
