# Generated by Django 2.2.2 on 2019-06-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0018_auto_20190627_2045')]

    operations = [
        migrations.AddField(
            model_name='task', name='submissions_public', field=models.BooleanField(default=False)
        )
    ]
