# Generated by Django 2.2.2 on 2019-06-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_task_submissions_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='recipient',
            field=models.EmailField(max_length=254),
        ),
    ]
