# Generated by Django 2.2.2 on 2019-07-09 04:37

from django.db import migrations


def invert_challenge_locked(apps, schema_editor):
    Challenge = apps.get_model('core', 'Challenge')  # noqa: N806
    for challenge in Challenge.objects.all():
        challenge.locked = not challenge.locked
        challenge.save()


def invert_task_hidden(apps, schema_editor):
    Task = apps.get_model('core', 'Task')  # noqa: N806
    for task in Task.objects.all():
        task.hidden = not task.hidden
        task.save()


def invert_task_locked(apps, schema_editor):
    Task = apps.get_model('core', 'Task')  # noqa: N806
    for task in Task.objects.all():
        task.locked = not task.locked
        task.save()


class Migration(migrations.Migration):

    dependencies = [('core', '0019_task_submissions_public')]

    operations = [
        migrations.RenameField(model_name='challenge', old_name='active', new_name='locked'),
        migrations.RunPython(invert_challenge_locked, invert_challenge_locked),
        migrations.RenameField(model_name='task', old_name='public', new_name='hidden'),
        migrations.RunPython(invert_task_hidden, invert_task_hidden),
        migrations.RenameField(model_name='task', old_name='active', new_name='locked'),
        migrations.RunPython(invert_task_locked, invert_task_locked),
        migrations.RenameField(
            model_name='task', old_name='submissions_public', new_name='scores_published'
        ),
    ]
