# Generated by Django 2.2.2 on 2019-07-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0020_auto_20190709_0437')]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='locked',
            field=models.BooleanField(
                default=True, help_text='Whether users are blocked from making and editing teams.'
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='hidden',
            field=models.BooleanField(
                default=True, help_text='Whether the task is invisible to users.'
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='locked',
            field=models.BooleanField(
                default=True,
                help_text='Whether users are blocked from making and editing '
                'approaches and submissions.',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='scores_published',
            field=models.BooleanField(
                default=False,
                help_text='Whether final scores are visible to submitters and the '
                'leaderboard is open.',
            ),
        ),
    ]
