# Generated by Django 2.2.2 on 2019-07-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190709_0439'),
        ('core', '0020_auto_20190627_2214'),
    ]

    operations = [
    ]
