# Generated by Django 2.2.2 on 2019-07-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0022_auto_20190709_1703')]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(
                choices=[('segmentation', 'Segmentation'), ('classification', 'Classification')],
                default='classification',
                max_length=20,
            ),
            preserve_default=False,
        )
    ]
