# Generated by Django 2.2.2 on 2019-07-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_merge_20190711_2117'),
        ('core', '0022_auto_20190709_1703'),
    ]

    operations = [
    ]
