# Generated by Django 2.2.2 on 2019-07-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0022_auto_20190709_1703')]

    operations = [
        migrations.AddField(
            model_name='task',
            name='max_approaches',
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text='The maximum number of approaches a team can make on this task.',
                verbose_name='Maxium Approaches',
            ),
        )
    ]
