# Generated by Django 2.2.2 on 2019-07-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0023_task_max_approaches')]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation', name='recipient', field=models.EmailField(max_length=254)
        )
    ]
