# Generated by Django 2.2.2 on 2019-07-16 17:59

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0024_auto_20190715_1536')]

    operations = [
        migrations.AlterField(
            model_name='approach',
            name='manuscript',
            field=models.FileField(
                blank=True,
                max_length=200,
                upload_to=core.models.manuscript_csv_file_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])
                ],
            ),
        )
    ]
