# Generated by Django 2.2.2 on 2019-07-16 19:23
from typing import List

from django.db import migrations
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):

    dependencies = [('core', '0026_auto_20190716_1449'), ('core', '0026_auto_20190716_1916')]

    operations: List[Operation] = []
