# Generated by Django 2.2.2 on 2019-07-18 18:22
from uuid import uuid4

import boto3
from django.conf import settings
import django.core.validators
from django.db import migrations

import core.models

s3 = boto3.resource('s3')


def migrate_s3_files(apps, schema_editor):
    Approach = apps.get_model('core', 'Approach')  # noqa
    Submission = apps.get_model('core', 'Submission')  # noqa

    for approach in (
        Approach.objects.exclude(manuscript_name__isnull=True)
        .exclude(manuscript_name__exact='')
        .all()
    ):
        old_name = approach.manuscript.name
        new_name = f'{uuid4()}/{approach.manuscript_name}'
        approach.manuscript.name = new_name
        print(f'{old_name} -> {new_name}')
        s3.Object(settings.AWS_STORAGE_BUCKET_NAME, new_name).copy_from(
            CopySource=f'{settings.AWS_STORAGE_BUCKET_NAME}/{old_name}'
        )
        approach.save()

    for submission in (
        Submission.objects.exclude(test_prediction_file_name__isnull=True)
        .exclude(test_prediction_file_name__exact='')
        .all()
    ):
        old_name = submission.test_prediction_file.name
        new_name = f'{uuid4()}/{submission.test_prediction_file_name}'
        submission.test_prediction_file.name = new_name
        print(f'{old_name} -> {new_name}')
        s3.Object(settings.AWS_STORAGE_BUCKET_NAME, new_name).copy_from(
            CopySource=f'{settings.AWS_STORAGE_BUCKET_NAME}/{old_name}'
        )
        submission.save()


class Migration(migrations.Migration):

    dependencies = [('core', '0027_merge_20190716_1923')]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='test_prediction_file',
            field=core.models.CollisionSafeFileField(
                max_length=200, upload_to=core.models.CollisionSafeFileField.uuid_prefix_filename
            ),
        ),
        migrations.RunPython(migrate_s3_files),
        migrations.RemoveField(model_name='approach', name='manuscript_name'),
        migrations.RemoveField(model_name='submission', name='test_prediction_file_name'),
        migrations.AlterField(
            model_name='approach',
            name='manuscript',
            field=core.models.CollisionSafeFileField(
                blank=True,
                max_length=200,
                upload_to=core.models.CollisionSafeFileField.uuid_prefix_filename,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])
                ],
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='test_ground_truth_file',
            field=core.models.CollisionSafeFileField(
                max_length=200, upload_to=core.models.CollisionSafeFileField.uuid_prefix_filename
            ),
        ),
    ]
