# Generated by Django 2.2.2 on 2019-07-22 17:05

from django.db import migrations


def merge_approaches(apps, schema_edito):
    approach = apps.get_model('core', 'Approach')
    submission = apps.get_model('core', 'Submission')

    cnn1 = approach.objects.get(pk=1143)
    cnn2 = approach.objects.get(pk=1144)
    cnn3 = approach.objects.get(pk=1145)
    if cnn1.created < cnn2.created and cnn1.created < cnn3.created:
        submission.objects.filter(approach=cnn2).update(approach=cnn1)
        cnn2.delete()
        submission.objects.filter(approach=cnn3).update(approach=cnn1)
        cnn3.delete()
    elif cnn2.created < cnn1.created and cnn2.created < cnn3.created:
        submission.objects.filter(approach=cnn1).update(approach=cnn2)
        cnn1.delete()
        submission.objects.filter(approach=cnn3).update(approach=cnn2)
        cnn3.delete()
    else:
        submission.objects.filter(approach=cnn1).update(approach=cnn3)
        cnn1.delete()
        submission.objects.filter(approach=cnn2).update(approach=cnn3)
        cnn2.delete()

    fcn1 = approach.objects.get(pk=169)
    fcn2 = approach.objects.get(pk=186)
    if fcn1.created < fcn2.created:
        submission.objects.filter(approach=fcn2).update(approach=fcn1)
        fcn2.delete()
    else:
        submission.objects.filter(approach=fcn1).update(approach=fcn2)
        fcn1.delete()

    gtdl1 = approach.objects.get(pk=40)
    gtdl2 = approach.objects.get(pk=41)
    if gtdl1.created < gtdl2.created:
        submission.objects.filter(approach=gtdl2).update(approach=gtdl1)
        gtdl2.delete()
    else:
        submission.objects.filter(approach=gtdl1).update(approach=gtdl2)
        gtdl1.delete()

    deeplab1 = approach.objects.get(pk=454)
    deeplab2 = approach.objects.get(pk=460)
    if deeplab1.created < deeplab2.created:
        submission.objects.filter(approach=deeplab2).update(approach=deeplab1)
        deeplab2.delete()
    else:
        submission.objects.filter(approach=deeplab1).update(approach=deeplab2)
        deeplab1.delete()


class Migration(migrations.Migration):

    dependencies = [('core', '0028_refactor_file_fields')]

    operations = [migrations.RunPython(merge_approaches)]
