# Generated by Django 2.2.2 on 2019-07-25 15:53

from django.db import migrations
from django.db.models import F, Q


def set_usernames_to_email_addresses(apps, schema_editor):
    User = apps.get_model('auth', 'User')  # noqa: N806

    for user in User.objects.filter(~Q(username=F('email'))):
        user.username = user.email
        user.save()


class Migration(migrations.Migration):

    dependencies = [('core', '0030_unique_constraint_approaches')]

    operations = [migrations.RunPython(set_usernames_to_email_addresses)]
