# Generated by Django 2.2.2 on 2019-07-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0031_coerce_usernames_to_email_addresses')]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='recipient',
            field=models.EmailField(db_index=True, max_length=254),
        )
    ]
