# Generated by Django 2.2.2 on 2019-08-09 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def accept_existing_approaches(apps, schema_editor):
    Approach = apps.get_model('core', 'Approach')  # noqa

    # approaches from ISIC 2016, 2017,and 2018
    to_be_accepted_approaches = Approach.objects.filter(task__challenge_id__in=[34, 35, 36])

    for approach in to_be_accepted_approaches:
        approach.review_state = 'accepted'
        approach.save()

    # intentionally leave review history blank, there is no history of when or who approved
    # past approaches


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_submission_validation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='review_state',
            field=models.CharField(
                blank=True,
                choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')],
                default='',
                max_length=8,
            ),
        ),
        migrations.RunPython(accept_existing_approaches),
        migrations.CreateModel(
            name='ReviewHistory',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'review_state',
                    models.CharField(
                        choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=8
                    ),
                ),
                (
                    'approach',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='review_history',
                        to='core.Approach',
                    ),
                ),
                (
                    'reviewed_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={'ordering': ['-created']},
        ),
    ]
