# Generated by Django 2.2.2 on 2019-08-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0035_add_approach_reviews')]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='reject_reason',
            field=models.CharField(
                blank=True,
                choices=[
                    ('blank_or_corrupt_manuscript', 'Blank/Corrupt manuscript'),
                    ('low_quality_manuscript', 'Low quality manuscript'),
                    ('rule_violation', 'Violation of rules'),
                ],
                default='',
                max_length=27,
            ),
        ),
        migrations.AddField(
            model_name='reviewhistory',
            name='reject_reason',
            field=models.CharField(
                blank=True,
                choices=[
                    ('blank_or_corrupt_manuscript', 'Blank/Corrupt manuscript'),
                    ('low_quality_manuscript', 'Low quality manuscript'),
                    ('rule_violation', 'Violation of rules'),
                ],
                default='',
                max_length=27,
            ),
        ),
        migrations.AlterField(
            model_name='approach',
            name='uses_external_data',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
