# Generated by Django 2.2.2 on 2019-08-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0036_add_reject_reason')]

    operations = [
        migrations.AlterField(
            model_name='approach',
            name='reject_reason',
            field=models.CharField(
                blank=True,
                choices=[
                    ('blank_or_corrupt_manuscript', 'Blank or corrupt manuscript'),
                    ('low_quality_manuscript', 'Low quality manuscript'),
                    ('rule_violation', 'Violation of rules'),
                ],
                default='',
                max_length=27,
            ),
        ),
        migrations.AlterField(
            model_name='reviewhistory',
            name='reject_reason',
            field=models.CharField(
                blank=True,
                choices=[
                    ('blank_or_corrupt_manuscript', 'Blank or corrupt manuscript'),
                    ('low_quality_manuscript', 'Low quality manuscript'),
                    ('rule_violation', 'Violation of rules'),
                ],
                default='',
                max_length=27,
            ),
        ),
    ]
