# Generated by Django 2.2.2 on 2019-08-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('core', '0037_rename_label')]

    operations = [
        # fmt: off
        migrations.RunSQL(
            """
create or replace view view_submission_approach as (
select t.task_id, t.approach_id, t.team_id, t.review_state, t.submission_id, t.overall_score
            from (
                    SELECT core_approach.task_id,
                           core_approach.id      approach_id,
                           core_approach.team_id      team_id,
                           core_approach.review_state review_state,
                           core_submission.id AS submission_id,
                           core_submission.overall_score AS overall_score,
                           ROW_NUMBER() OVER w AS rn
                    FROM core_approach
                             INNER JOIN core_submission ON
            core_submission.approach_id = core_approach.id
                    WHERE core_submission.status = 'succeeded' WINDOW w AS (PARTITION BY
            core_approach.id ORDER BY core_submission.created DESC)
                ) t where t.rn =1);
            """
        ),
        # fmt: on
        migrations.CreateModel(
            name='SubmissionApproach',
            fields=[
                (
                    'submission',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to='core.Submission',
                    ),
                ),
                ('review_state', models.CharField(max_length=27)),
                ('overall_score', models.FloatField()),
            ],
            options={'db_table': 'view_submission_approach', 'managed': False},
        )
    ]
