# Generated by Django 2.2.2 on 2019-08-19 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('core', '0039_add_approach_reviewer')]

    operations = [migrations.DeleteModel(name='ScoreHistory')]
