# Generated by Django 2.2.4 on 2019-11-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('core', '0039_remove_score_history')]

    operations = [migrations.AlterModelOptions(name='task', options={'ordering': ['id']})]
