# Generated by Django 2.2.4 on 2019-11-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0040_change_task_ordering')]

    operations = [
        migrations.AddField(
            model_name='task',
            name='requires_manuscript',
            field=models.BooleanField(
                default=True,
                help_text='Whether approaches should require a manuscript.',
                verbose_name='Requires a manuscript',
            ),
        )
    ]
