# Generated by Django 2.2.8 on 2019-12-05 02:43

import django.core.validators
from django.db import migrations
import joist.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_requires_manuscript_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approach',
            name='manuscript',
            field=joist.models.S3FileField(
                blank=True,
                max_length=2000,
                upload_to=joist.models.S3FileField.uuid_prefix_filename,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])
                ],
            ),
        ),
        migrations.AlterField(
            model_name='submission',
            name='test_prediction_file',
            field=joist.models.S3FileField(
                max_length=2000, upload_to=joist.models.S3FileField.uuid_prefix_filename
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='test_ground_truth_file',
            field=joist.models.S3FileField(
                max_length=2000, upload_to=joist.models.S3FileField.uuid_prefix_filename
            ),
        ),
    ]
