# Generated by Django 3.0.2 on 2020-01-28 19:17

from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [('core', '0041_add_requires_manuscript_column')]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='test_ground_truth_file',
            field=s3_file_field.fields.S3FileField(
                max_length=2000, upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename
            ),
        )
    ]
