# Generated by Django 3.0.2 on 2020-01-30 15:34

import django.core.validators
from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [('core', '0042_task_use_s3ff')]

    operations = [
        migrations.AlterField(
            model_name='approach',
            name='manuscript',
            field=s3_file_field.fields.S3FileField(
                blank=True,
                max_length=2000,
                upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])
                ],
            ),
        ),
        migrations.AlterField(
            model_name='submission',
            name='test_prediction_file',
            field=s3_file_field.fields.S3FileField(
                max_length=2000, upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename
            ),
        ),
    ]
