# Generated by Django 3.0.3 on 2020-02-07 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_convert_to_s3ff_fields'),
    ]

    operations = [
        migrations.DeleteModel(name='SubmissionApproach',),
        migrations.RunSQL('drop view if exists view_submission_approach;'),
    ]
