# Generated by Django 3.0.3 on 2020-02-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0001_initial')]

    operations = [
        migrations.AddField(model_name='challenge', name='slug', field=models.SlugField(blank=True))
    ]
