# Generated by Django 3.1.2 on 2020-11-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_submission_score_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='metric_field',
            field=models.CharField(
                choices=[
                    ('balanced_accuracy', 'Balanced Accuracy'),
                    ('ap', 'Average Precision'),
                    ('auc', 'AUC'),
                ],
                default='auc',
                help_text='Which metric to use for the overall score',
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
