# Generated by Django 3.1.2 on 2020-12-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_submission_score_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='creator_fingerprint',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='creator_fingerprint_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
