# Generated by Django 3.1.2 on 2020-12-03 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_fingerprinting'),
        ('core', '0007_add_scoring_field'),
    ]

    operations = []
