# Generated by Django 3.1.5 on 2021-01-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hidden',
            field=models.BooleanField(
                default=True, help_text='Whether the GUI exposes this task to users.'
            ),
        ),
    ]
