# Generated by Django 5.2.4 on 2025-07-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_approach_id_alter_challenge_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='metric_field',
            field=models.CharField(
                choices=[
                    ('balanced_accuracy', 'Balanced Accuracy'),
                    ('ap', 'Average Precision'),
                    ('auc', 'AUC'),
                    ('dice', 'Dice Coefficient'),
                ],
                help_text='Which metric to use for the overall score',
                max_length=100,
            ),
        ),
    ]
