# Generated by Django 5.2.5 on 2025-08-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_task_metric_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
